// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package config

import (
	"github.com/ProtocolONE/go-core/v2/pkg/invoker"
)

// Injectors from injector.go:

func Build(initial Initial, observer invoker.Observer) (Configurator, func(), error) {
	configurator, cleanup, err := Provider(initial, observer)
	if err != nil {
		return nil, nil, err
	}
	return configurator, func() {
		cleanup()
	}, nil
}

func BuildTest(initial Initial, observer invoker.Observer, settings Settings) (Configurator, func(), error) {
	configurator, cleanup, err := ProviderTest(initial, observer, settings)
	if err != nil {
		return nil, nil, err
	}
	return configurator, func() {
		cleanup()
	}, nil
}
